# Generated by Django 5.0.3 on 2024-03-30 18:37

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assents/favicon/%Y/%m', validators=[utils.model_validators.validate_png]),
        ),
    ]
